name: deploy dm.reflector to prod

on:
  push:
    branches: [ master ]
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
    - run: set -eu
    - name: setup ssh key
      run: |
        mkdir "$HOME/.ssh"
        echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/key"
        chmod 600 "$HOME/.ssh/key"
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: initi remote repo
      run: |
        GIT_SSH_COMMAND="ssh -i $HOME/.ssh/key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone cloudnode@git.cloudno.de:/git/detect-me.tech/9091-54b981ecfc111f5a7343006498541e01.git
    - name: build app
      run: |
        GIT_SSH_COMMAND="ssh -i $HOME/.ssh/key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" npm install
        npm run build
    - name: push-to-remote
      run: |
        cp app.js 9091-54b981ecfc111f5a7343006498541e01
        cp -R dist 9091-54b981ecfc111f5a7343006498541e01
        cd 9091-54b981ecfc111f5a7343006498541e01
        git config --global user.email "detectme-tech@gmail.com"
        git config --global user.name "detectme-tech"
        git add app.js dist
        git commit -m  "released $GITHUB_RUN_NUMBER version"
        GIT_SSH_COMMAND="ssh -i $HOME/.ssh/key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push origin master
